### ISSUE TITLE
Alteração no caminho do svg no código de Paginação

### ISSUE THREAD

**Issue by agawebdesign** [aleguarita/Front-Alego#32]
*_É necessário adicionar o endereço da pasta assets no caminho do svg. Segue o código da Paginação já alterado: 
*_

```
 views:
    pagination:
      first: "<span title='Primeira Página'><svg class='ico--esquerda'><use xlink:href='/assets/ico.svg#seta-dupla' /></svg></span>"
      last: "<span title='Última Página'><svg class='ico'><use xlink:href='/assets/ico.svg#seta-dupla' /></svg></span>"
      previous: "<span title='Anterior'><svg class='ico--esquerda'><use xlink:href='/assets/ico.svg#seta-fina' /></svg></span>"
      next: "<span title='Próxima'><svg class='ico'><use xlink:href='/assets/ico.svg#seta-fina' /></svg></span>"
      truncate: "..."
```
